### PR TITLE
List events alphabetically

### PR DESCRIPTION
**Pull request by mertzjl91**
Most of this is the same as the search events code.

### CODE REVIEW

**Comment by miketully426** [comment]
Same here! I  I don't see any code to display events alphabetically.

**Comment by miketully426** [comment]
> Same here! I I don't see any code to display events alphabetically.

DISREGARD! 🤦‍♂️

**Review by aeydie — COMMENTED** [review]
Code functioned with testing!  :)

**Review by lfallert — APPROVED** [review]
Tested and working correctly (events listed alphabetically, with symbols and numbers first, followed by letters). Great job!

**Review by CNichole726 — APPROVED** [review]
Looks good to me!

**Review by aeydie — APPROVED** [review]
All events are listing appropriately - tried numbers and symbols and all worked as they should.  I removed a few imports that weren't being used out of the event class in IntelliJ and pushed the changes to this branch.  Looks good! In event.ts - does it need to list id - or eventId as the variable for an event's id.  I think for this feature that isn't mattering but wanted to mention it.

**Pull request merged**
